"""PlanStateMachine — enforces valid lifecycle transitions for Plan objects.

Follows the same design as MemoryStateMachine in app/services/state.py.

Valid transitions:
    DRAFT       → APPROVED, ABANDONED
    APPROVED    → EXECUTING, ABANDONED
    EXECUTING   → COMPLETED, ABANDONED
    COMPLETED   → (terminal)
    ABANDONED   → (terminal)

Note: Plans are generated by the AI. Execution belongs to future Agent milestones (M5).
"""

import uuid
from typing import Dict, List

import structlog

from app.models.enums import PlanStatus
from app.models.exceptions import InvalidPlanTransitionError

logger = structlog.get_logger(__name__)


class PlanStateMachine:
    """Enforces valid state transitions for Plan lifecycle."""

    VALID_TRANSITIONS: Dict[PlanStatus, List[PlanStatus]] = {
        PlanStatus.DRAFT: [
            PlanStatus.APPROVED,
            PlanStatus.ABANDONED,
        ],
        PlanStatus.APPROVED: [
            PlanStatus.EXECUTING,
            PlanStatus.ABANDONED,
        ],
        PlanStatus.EXECUTING: [
            PlanStatus.COMPLETED,
            PlanStatus.ABANDONED,
        ],
        PlanStatus.COMPLETED: [],  # Terminal
        PlanStatus.ABANDONED: [],  # Terminal
    }

    @classmethod
    def transition(
        cls,
        plan_id: uuid.UUID,
        current_status: PlanStatus,
        target_status: PlanStatus,
    ) -> PlanStatus:
        """Validate and execute a state transition.

        Returns the new status if valid.
        Raises InvalidPlanTransitionError if the transition is not allowed.
        """
        if target_status not in cls.VALID_TRANSITIONS.get(current_status, []):
            logger.error(
                "Invalid plan state transition attempted",
                plan_id=str(plan_id),
                current_status=current_status.value,
                target_status=target_status.value,
            )
            raise InvalidPlanTransitionError(
                current=current_status.value,
                target=target_status.value,
                plan_id=str(plan_id),
            )

        logger.info(
            "Plan state transition approved",
            plan_id=str(plan_id),
            from_status=current_status.value,
            to_status=target_status.value,
        )
        return target_status
