from typing import List

from pydantic import BaseModel, Field


class SituationRisk(BaseModel):
    risk_id: str
    description: str
    severity: str

class SituationOpportunity(BaseModel):
    opportunity_id: str
    description: str
    potential_value: str

class SituationGap(BaseModel):
    gap_id: str
    description: str

class SituationAssessment(BaseModel):
    """Overall assessment generated by the Situation Analysis Engine."""
    summary: str
    risks: list[SituationRisk] = Field(default_factory=list)
    opportunities: list[SituationOpportunity] = Field(default_factory=list)
    missing_information: list[SituationGap] = Field(default_factory=list)
