from pydantic import BaseModel, Field
from typing import List

class SituationRisk(BaseModel):
    risk_id: str
    description: str
    severity: str

class SituationOpportunity(BaseModel):
    opportunity_id: str
    description: str
    potential_value: str

class SituationGap(BaseModel):
    gap_id: str
    description: str

class SituationAssessment(BaseModel):
    """Overall assessment generated by the Situation Analysis Engine."""
    summary: str
    risks: List[SituationRisk] = Field(default_factory=list)
    opportunities: List[SituationOpportunity] = Field(default_factory=list)
    missing_information: List[SituationGap] = Field(default_factory=list)
