from dataclasses import dataclass
from enum import StrEnum

from pydantic import Field

from app.domain.intelligence.context import IntelligenceContext
from app.domain.intelligence.provider import IIntelligenceProvider
from app.domain.intelligence.telemetry import IntelligenceMetrics
from app.intelligence.executive.workflow import Workflow


class WorkflowState(StrEnum):
    """Execution state of the workflow intelligence evaluation."""
    ANALYZING = "ANALYZING"
    OPTIMIZING = "OPTIMIZING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class WorkflowOptimizationContext(IntelligenceContext):
    """Context passing through the Workflow Intelligence pipeline."""
    workflow: Workflow
    optimization_suggestions: list[str] = Field(default_factory=list)
    state: WorkflowState = Field(default=WorkflowState.ANALYZING)

    class Config:
        arbitrary_types_allowed = True


class WorkflowOptimizationMetrics(IntelligenceMetrics):
    """Telemetry for workflow optimization operations."""
    optimization_time_ms: float = 0.0
    tasks_optimized_count: int = 0


@dataclass
class WorkflowOptimizationResult:
    """The result generated by a workflow optimizer."""
    success: bool
    optimized_workflow: Workflow
    metrics: WorkflowOptimizationMetrics
    error_message: str | None = None


import abc

class IWorkflowIntelligenceProvider(IIntelligenceProvider, abc.ABC):
    """Abstract interface for capabilities that can optimize a workflow."""

    @abc.abstractmethod
    async def optimize(self, context: WorkflowOptimizationContext) -> WorkflowOptimizationResult:
        """Analyze and optimize the workflow DAG."""
        pass
