"""Metrics and Observer for LLM Providers.

This module provides Prometheus metrics for LLM operations and a ProviderObserver
decorator/wrapper that transparently records metrics for any ILLMProvider.
"""

import time
import uuid
from collections.abc import AsyncIterator
from typing import Any, TypeVar

import structlog
from prometheus_client import Counter, Histogram
from pydantic import BaseModel

from app.infrastructure.ai.models import (
    AIRequest,
    AIResponse,
    EmbeddingRequest,
    EmbeddingResponse,
    ProviderError,
    StreamChunk,
    StructuredRequest,
)
from app.infrastructure.ai.providers.base import ILLMProvider, ProviderCapabilities

logger = structlog.get_logger(__name__)

T = TypeVar("T", bound=BaseModel)

# Prometheus Metrics Definitions
LLM_TOKENS_IN = Counter(
    "bizos_llm_tokens_in_total",
    "Total input tokens sent to LLM providers",
    ["provider", "model", "operation"]
)

LLM_TOKENS_OUT = Counter(
    "bizos_llm_tokens_out_total",
    "Total output tokens generated by LLM providers",
    ["provider", "model", "operation"]
)

LLM_REQUEST_DURATION = Histogram(
    "bizos_llm_request_duration_seconds",
    "LLM request duration in seconds",
    ["provider", "model", "operation"],
    buckets=[0.1, 0.5, 1.0, 2.0, 5.0, 10.0, 30.0, 60.0]
)

LLM_ESTIMATED_COST = Counter(
    "bizos_llm_estimated_cost_usd",
    "Estimated cost in USD of LLM operations",
    ["provider", "model", "operation"]
)

LLM_ERRORS = Counter(
    "bizos_llm_errors_total",
    "Total errors from LLM providers",
    ["provider", "model", "operation", "error_type"]
)

LLM_FALLBACK_ACTIVATIONS = Counter(
    "bizos_llm_fallback_activations_total",
    "Total times a fallback provider was activated",
    ["primary_provider", "fallback_provider"]
)

LLM_BUDGET_REJECTIONS = Counter(
    "bizos_llm_budget_rejections_total",
    "Total times a request was rejected due to budget constraints",
    ["provider", "budget_type"]
)

LLM_STRUCTURED_OUTPUT_FAILURES = Counter(
    "bizos_llm_structured_output_failures_total",
    "Total times structured output validation failed",
    ["provider", "model"]
)


class ProviderObserver(ILLMProvider):
    """Transparent wrapper for any ILLMProvider that adds observability."""

    def __init__(self, provider: ILLMProvider):
        """Initialize the observer with the target provider."""
        self._provider = provider

    @property
    def provider_name(self) -> str:
        return self._provider.provider_name

    @property
    def capabilities(self) -> ProviderCapabilities:
        return self._provider.capabilities

    def _get_model(self, request: Any, default_model: str) -> str:
        """Extract the model from a request, falling back to provider default."""
        return getattr(request, "model", None) or default_model

    async def generate(self, request: AIRequest, prompt_text: str) -> AIResponse:
        """Generate text with observability."""
        operation = "generate"
        model = self._get_model(request, self.capabilities.default_generation_model)

        # Ensure a lifecycle ID is present in the request or generate one for tracing
        lifecycle_id = request.lifecycle.lifecycle_id if request.lifecycle else str(uuid.uuid4())

        start_time = time.perf_counter()

        # Bind the lifecycle ID to the structlog context for the duration of the call
        # No prompt content is logged, only metadata
        log = logger.bind(lifecycle_id=lifecycle_id, provider=self.provider_name, operation=operation)
        log.info("llm_generate_started")

        try:
            response = await self._provider.generate(request, prompt_text)
            duration = time.perf_counter() - start_time

            # Record metrics
            LLM_REQUEST_DURATION.labels(self.provider_name, model, operation).observe(duration)

            if response.metadata.prompt_tokens is not None:
                LLM_TOKENS_IN.labels(self.provider_name, model, operation).inc(response.metadata.prompt_tokens)

            if response.metadata.completion_tokens is not None:
                LLM_TOKENS_OUT.labels(self.provider_name, model, operation).inc(response.metadata.completion_tokens)

            log.info(
                "llm_generate_completed",
                duration_s=duration,
                prompt_tokens=response.metadata.prompt_tokens,
                completion_tokens=response.metadata.completion_tokens
            )
            return response

        except ProviderError as e:
            duration = time.perf_counter() - start_time
            error_type = type(e).__name__
            LLM_REQUEST_DURATION.labels(self.provider_name, model, operation).observe(duration)
            LLM_ERRORS.labels(self.provider_name, model, operation, error_type).inc()
            log.error("llm_generate_failed", duration_s=duration, error_type=error_type, error=str(e))
            raise
        except Exception as e:
            duration = time.perf_counter() - start_time
            error_type = type(e).__name__
            LLM_REQUEST_DURATION.labels(self.provider_name, model, operation).observe(duration)
            LLM_ERRORS.labels(self.provider_name, model, operation, error_type).inc()
            log.error("llm_generate_failed_unexpected", duration_s=duration, error_type=error_type, error=str(e))
            raise

    async def generate_structured(self, request: StructuredRequest[T]) -> T:
        """Generate structured text with observability."""
        operation = "generate_structured"
        model = self._get_model(request, self.capabilities.default_generation_model)

        lifecycle_id = request.lifecycle.lifecycle_id if request.lifecycle else str(uuid.uuid4())
        start_time = time.perf_counter()
        log = logger.bind(lifecycle_id=lifecycle_id, provider=self.provider_name, operation=operation)
        log.info("llm_generate_structured_started")

        try:
            response = await self._provider.generate_structured(request)
            duration = time.perf_counter() - start_time

            LLM_REQUEST_DURATION.labels(self.provider_name, model, operation).observe(duration)
            # Cannot accurately track tokens for structured output if the underlying
            # provider doesn't expose them in the parsed result.
            # Some providers might, but we only have the Pydantic model here.

            log.info("llm_generate_structured_completed", duration_s=duration)
            return response

        except ProviderError as e:
            duration = time.perf_counter() - start_time
            error_type = type(e).__name__
            LLM_REQUEST_DURATION.labels(self.provider_name, model, operation).observe(duration)
            LLM_ERRORS.labels(self.provider_name, model, operation, error_type).inc()

            if error_type == "StructuredOutputError":
                LLM_STRUCTURED_OUTPUT_FAILURES.labels(self.provider_name, model).inc()

            log.error("llm_generate_structured_failed", duration_s=duration, error_type=error_type, error=str(e))
            raise
        except Exception as e:
            duration = time.perf_counter() - start_time
            error_type = type(e).__name__
            LLM_REQUEST_DURATION.labels(self.provider_name, model, operation).observe(duration)
            LLM_ERRORS.labels(self.provider_name, model, operation, error_type).inc()
            log.error("llm_generate_structured_failed_unexpected", duration_s=duration, error_type=error_type, error=str(e))
            raise

    async def stream(self, request: AIRequest, prompt_text: str) -> AsyncIterator[StreamChunk]:
        """Stream generated text chunk by chunk with observability."""
        operation = "stream"
        model = self._get_model(request, self.capabilities.default_generation_model)

        lifecycle_id = request.lifecycle.lifecycle_id if request.lifecycle else str(uuid.uuid4())
        start_time = time.perf_counter()
        log = logger.bind(lifecycle_id=lifecycle_id, provider=self.provider_name, operation=operation)
        log.info("llm_stream_started")

        try:
            async for chunk in self._provider.stream(request, prompt_text):
                yield chunk

                if chunk.is_final:
                    duration = time.perf_counter() - start_time
                    LLM_REQUEST_DURATION.labels(self.provider_name, model, operation).observe(duration)

                    if chunk.prompt_tokens is not None:
                        LLM_TOKENS_IN.labels(self.provider_name, model, operation).inc(chunk.prompt_tokens)

                    if chunk.completion_tokens is not None:
                        LLM_TOKENS_OUT.labels(self.provider_name, model, operation).inc(chunk.completion_tokens)

                    log.info(
                        "llm_stream_completed",
                        duration_s=duration,
                        prompt_tokens=chunk.prompt_tokens,
                        completion_tokens=chunk.completion_tokens
                    )
        except ProviderError as e:
            duration = time.perf_counter() - start_time
            error_type = type(e).__name__
            LLM_REQUEST_DURATION.labels(self.provider_name, model, operation).observe(duration)
            LLM_ERRORS.labels(self.provider_name, model, operation, error_type).inc()
            log.error("llm_stream_failed", duration_s=duration, error_type=error_type, error=str(e))
            raise
        except Exception as e:
            duration = time.perf_counter() - start_time
            error_type = type(e).__name__
            LLM_REQUEST_DURATION.labels(self.provider_name, model, operation).observe(duration)
            LLM_ERRORS.labels(self.provider_name, model, operation, error_type).inc()
            log.error("llm_stream_failed_unexpected", duration_s=duration, error_type=error_type, error=str(e))
            raise

    async def embed(self, request: EmbeddingRequest) -> EmbeddingResponse:
        """Generate a vector embedding with observability."""
        operation = "embed"
        model = getattr(request, "model", None) or self.capabilities.default_embedding_model

        lifecycle_id = str(uuid.uuid4())  # EmbeddingRequests don't currently have a lifecycle model
        start_time = time.perf_counter()
        log = logger.bind(lifecycle_id=lifecycle_id, provider=self.provider_name, operation=operation)
        log.info("llm_embed_started")

        try:
            response = await self._provider.embed(request)
            duration = time.perf_counter() - start_time

            LLM_REQUEST_DURATION.labels(self.provider_name, model, operation).observe(duration)

            if response.metadata.prompt_tokens is not None:
                LLM_TOKENS_IN.labels(self.provider_name, model, operation).inc(response.metadata.prompt_tokens)

            log.info("llm_embed_completed", duration_s=duration, prompt_tokens=response.metadata.prompt_tokens)
            return response

        except ProviderError as e:
            duration = time.perf_counter() - start_time
            error_type = type(e).__name__
            LLM_REQUEST_DURATION.labels(self.provider_name, model, operation).observe(duration)
            LLM_ERRORS.labels(self.provider_name, model, operation, error_type).inc()
            log.error("llm_embed_failed", duration_s=duration, error_type=error_type, error=str(e))
            raise
        except Exception as e:
            duration = time.perf_counter() - start_time
            error_type = type(e).__name__
            LLM_REQUEST_DURATION.labels(self.provider_name, model, operation).observe(duration)
            LLM_ERRORS.labels(self.provider_name, model, operation, error_type).inc()
            log.error("llm_embed_failed_unexpected", duration_s=duration, error_type=error_type, error=str(e))
            raise

    async def count_tokens(self, text: str, model: str | None = None) -> int:
        """Count tokens with observability."""
        operation = "count_tokens"
        resolved_model = model or self.capabilities.default_generation_model

        lifecycle_id = str(uuid.uuid4())
        start_time = time.perf_counter()
        log = logger.bind(lifecycle_id=lifecycle_id, provider=self.provider_name, operation=operation)
        log.debug("llm_count_tokens_started")

        try:
            tokens = await self._provider.count_tokens(text, model)
            duration = time.perf_counter() - start_time

            LLM_REQUEST_DURATION.labels(self.provider_name, resolved_model, operation).observe(duration)
            log.debug("llm_count_tokens_completed", duration_s=duration, tokens=tokens)
            return tokens

        except ProviderError as e:
            duration = time.perf_counter() - start_time
            error_type = type(e).__name__
            LLM_REQUEST_DURATION.labels(self.provider_name, resolved_model, operation).observe(duration)
            LLM_ERRORS.labels(self.provider_name, resolved_model, operation, error_type).inc()
            log.error("llm_count_tokens_failed", duration_s=duration, error_type=error_type, error=str(e))
            raise
        except Exception as e:
            duration = time.perf_counter() - start_time
            error_type = type(e).__name__
            LLM_REQUEST_DURATION.labels(self.provider_name, resolved_model, operation).observe(duration)
            LLM_ERRORS.labels(self.provider_name, resolved_model, operation, error_type).inc()
            log.error("llm_count_tokens_failed_unexpected", duration_s=duration, error_type=error_type, error=str(e))
            raise

    async def health_check(self) -> dict[str, Any]:
        """Verify provider connectivity and configuration, passing through transparently."""
        return await self._provider.health_check()
